"""empty message

Revision ID: 33ef9df9bc1f
Revises: a9f7211d51b8
Create Date: 2024-03-30 13:36:48.307885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ef9df9bc1f'
down_revision = 'a9f7211d51b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_data', sa.DateTime(), nullable=False))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_data', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('create_data')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('create_data')

    # ### end Alembic commands ###
